Check if index.js was built before commit

diff --git a/.github/workflows/publish-master.yml b/.github/workflows/publish-master.yml
--- a/.github/workflows/publish-master.yml
+++ b/.github/workflows/publish-master.yml
@@ -34,6 +34,13 @@ jobs:
         run: npm run build
       - name: Run Unit Tests
         run: npm run test
+      - name: "Check if the index.js was built before check-in"
+        # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
+        run: |
+          git diff --exit-code --stat -- . ':!node_modules' \
+          || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
+                    "and check in all changes" \
+              && exit 1)
         
       # - name: get email
       #   id: getemail
